// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTYj9KCyEhBwcuW37QmnZpgHuuk48mOXU',
    appId: '1:27754931683:web:1267c6291585397f25ecd6',
    messagingSenderId: '27754931683',
    projectId: 'simple-dice-app',
    authDomain: 'simple-dice-app.firebaseapp.com',
    storageBucket: 'simple-dice-app.appspot.com',
    measurementId: 'G-1JVQBL3L21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApwDPXqjiocNVWoR-m2VF9mJOck48k5-g',
    appId: '1:27754931683:android:0e081563e52c340625ecd6',
    messagingSenderId: '27754931683',
    projectId: 'simple-dice-app',
    storageBucket: 'simple-dice-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifRuhEvmPl1JsU2BEW6zhewcUYWiGI5I',
    appId: '1:27754931683:ios:9d570a9b2ab4ee9f25ecd6',
    messagingSenderId: '27754931683',
    projectId: 'simple-dice-app',
    storageBucket: 'simple-dice-app.appspot.com',
    iosClientId: '27754931683-6msslfre1p75og4ongd9niggt5eqssql.apps.googleusercontent.com',
    iosBundleId: 'com.naniinnovations.simpleDiceApp',
  );
}
